import type { Metadata } from "next";
import "./globals.css";
import type { NextLayoutProps } from "./type";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: NextLayoutProps) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
